apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  creationTimestamp: null
  name: argotest1
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "103"
  name: powerpod
  namespace: argotest1
spec:
  template:
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 30
      containers:
        - image: quay.io/sfhassan/newtools
          name: testjob
          command:
            - /bin/bash
            - -c
            - |
              while true; do echo "hello"; sleep 10; done
